import { getWeekNumber, formatDate } from "@loopkit/shared";
import {
  readTasksFile,
  readShipLog,
  readLastNLoopLogs,
  loopLogExists,
  saveLoopLog,
} from "../storage/local.js";

function getLastFridayDate(): string {
  const today = new Date();
  const dayOfWeek = today.getDay();
  const daysSinceFriday = (dayOfWeek + 2) % 7;
  const friday = new Date(today);
  friday.setDate(friday.getDate() - daysSinceFriday);
  return formatDate(friday);
}

export interface AutoLoopDraft {
  weekNumber: number;
  tasksCompleted: number;
  tasksOpen: number;
  shippingScore: number;
  shipped: boolean;
  suggestedOneThing: string;
  suggestedBipPost: string;
}

export function checkMissedSunday(slug: string): AutoLoopDraft | null {
  const today = new Date();
  const dayOfWeek = today.getDay();

  if (dayOfWeek !== 1) return null;

  const weekNum = getWeekNumber();
  if (loopLogExists(weekNum)) return null;

  const tasksContent = readTasksFile(slug);
  if (!tasksContent) return null;

  const lines = tasksContent.split("\n");
  let tasksCompleted = 0;
  let tasksOpen = 0;

  for (const line of lines) {
    if (/^\s*-\s*\[x\]/i.test(line)) tasksCompleted++;
    else if (/^\s*-\s*\[ \]/.test(line)) tasksOpen++;
  }

  const totalTasks = tasksCompleted + tasksOpen;
  const shippingScore = totalTasks > 0 ? Math.round((tasksCompleted / totalTasks) * 100) : 0;
  const shipped = !!readShipLog(getLastFridayDate());

  const completedTasks = lines
    .filter((l) => /^\s*-\s*\[x\]/i.test(l))
    .map((l) => l.replace(/^\s*-\s*\[x\]\s*/, "").trim());

  const openTasks = lines
    .filter((l) => /^\s*-\s*\[ \]/.test(l))
    .map((l) => l.replace(/^\s*-\s*\[ \]\s*/, "").trim());

  const suggestedOneThing = openTasks.length > 0
    ? openTasks[0]
    : "Review your brief and plan next week's validation task";

  const suggestedBipPost = shipped
    ? `Week ${weekNum}: Shipped ${tasksCompleted} tasks at ${shippingScore}% completion. Building in public, one week at a time.`
    : `Week ${weekNum}: ${tasksCompleted} tasks done, ${tasksOpen} still open. Shipping score ${shippingScore}%. Consistency > perfection.`;

  return {
    weekNumber: weekNum,
    tasksCompleted,
    tasksOpen,
    shippingScore,
    shipped,
    suggestedOneThing,
    suggestedBipPost,
  };
}

export function saveAutoLoopDraft(slug: string, draft: AutoLoopDraft): void {
  const logContent = [
    `# Week ${draft.weekNumber} — ${formatDate()} (auto-generated) | project:${slug}`,
    "",
    "## Summary",
    `- Tasks completed: ${draft.tasksCompleted}`,
    `- Tasks open: ${draft.tasksOpen}`,
    `- Shipping score: ${draft.shippingScore}%`,
    `- Shipped Friday: ${draft.shipped ? "Yes" : "No"}`,
    "",
    "## The One Thing",
    draft.suggestedOneThing,
    "",
    "_Auto-generated by Auto-Loop (missed Sunday ritual). Review and confirm._",
    "",
    "## BIP Post",
    draft.suggestedBipPost,
  ].join("\n");

  saveLoopLog(draft.weekNumber, logContent);
}
