import { type ProjectTemplate } from "@loopkit/shared";

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: "saas",
    name: "SaaS Product",
    description: "Subscription-based B2B or B2C software",
    icpHint: "Small team leads at 10–50 person companies who are overwhelmed by spreadsheets",
    taskScaffold: [
      "Set up auth (email + OAuth)",
      "Build waitlist landing page with value prop",
      "Configure Stripe billing (subscription model)",
      "Create core dashboard UI shell",
      "Set up production database schema",
      "Build user onboarding flow (3-step)",
      "Add email notifications (welcome + weekly digest)",
      "Write pricing page copy",
    ],
    category: "saas",
  },
  {
    id: "api",
    name: "Developer API",
    description: "Programmatic service other developers integrate",
    icpHint: "Developers at growth-stage startups who need to offload infrastructure",
    taskScaffold: [
      "Design REST API spec (OpenAPI)",
      "Build sandbox environment with rate limits",
      "Write interactive API documentation",
      "Create SDK wrapper (npm package)",
      "Set up API key management",
      "Build status page + changelog",
      "Add request/response examples",
      "Write 'Getting Started' guide",
    ],
    category: "api",
  },
  {
    id: "mobile",
    name: "Mobile App",
    description: "iOS or Android native or cross-platform app",
    icpHint: "Gen Z professionals aged 22–32 who want productivity on the go",
    taskScaffold: [
      "Set up project scaffold (React Native / Flutter)",
      "Build onboarding screens (3-slide)",
      "Configure push notifications",
      "Create core feature screen UI",
      "Set up app store assets (screenshots + description)",
      "Add offline persistence",
      "Build settings/profile screen",
      "Prepare TestFlight / internal testing build",
    ],
    category: "mobile",
  },
  {
    id: "cli",
    name: "CLI Tool",
    description: "Terminal-based developer tool or utility",
    icpHint: "Terminal-native developers who value speed over GUIs",
    taskScaffold: [
      "Set up CLI framework (commander + prompts)",
      "Build install script (curl | bash)",
      "Create comprehensive --help output",
      "Add configuration file support",
      "Write man page or README docs",
      "Set up Homebrew formula or npm publish",
      "Add shell completions (bash/zsh)",
      "Build update notifier",
    ],
    category: "cli",
  },
  {
    id: "newsletter",
    name: "Newsletter / Content",
    description: "Curated email or written content product",
    icpHint: "Executives seeking curated industry intel without the noise",
    taskScaffold: [
      "Set up landing page with email capture",
      "Configure newsletter platform (Beehiiv/Substack)",
      "Write first 3 issues as templates",
      "Create referral loop (share to unlock)",
      "Set up sponsorship inquiry page",
      "Build archive / search for past issues",
      "Add analytics (open rates, clicks)",
      "Write welcome email sequence (3 emails)",
    ],
    category: "newsletter",
  },
  {
    id: "agency",
    name: "Agency / Service",
    description: "Client services business with productized offerings",
    icpHint: "Startup founders who need design or dev help but can't hire full-time",
    taskScaffold: [
      "Build portfolio page (3 case studies)",
      "Set up CRM for leads (Notion/Airtable)",
      "Create proposal template",
      "Build invoicing workflow (Stripe / Wave)",
      "Write service tier descriptions",
      "Set up calendly / booking link",
      "Create onboarding questionnaire",
      "Add testimonials / social proof section",
    ],
    category: "agency",
  },
  {
    id: "open-source",
    name: "Open Source Project",
    description: "Public library, framework, or tool",
    icpHint: "Developers who value transparency and community-driven tools",
    taskScaffold: [
      "Write README with clear problem statement",
      "Add LICENSE (MIT/Apache)",
      "Set up CI/CD (GitHub Actions)",
      "Create CONTRIBUTING.md guidelines",
      "Add issue templates (bug + feature)",
      "Write API documentation",
      "Set up code of conduct",
      "Publish to package registry (npm/pypi/etc)",
    ],
    category: "open-source",
  },
  {
    id: "marketplace",
    name: "Marketplace",
    description: "Two-sided platform connecting buyers and sellers",
    icpHint: "Buyers and sellers in a niche vertical who struggle to find each other",
    taskScaffold: [
      "Build listing creation flow",
      "Set up search + filtering",
      "Configure escrow or direct payments",
      "Create reputation/rating system",
      "Add messaging between parties",
      "Build admin moderation dashboard",
      "Write trust & safety policy",
      "Set up commission/fee structure",
    ],
    category: "marketplace",
  },
  {
    id: "ai-wrapper",
    name: "AI Wrapper",
    description: "Productized interface on top of LLM or AI model",
    icpHint: "Non-technical professionals who want AI power without prompt engineering",
    taskScaffold: [
      "Set up LLM integration (OpenAI / Anthropic)",
      "Build prompt templates for core use case",
      "Create input form with validation",
      "Add output formatting + export",
      "Set up usage limits / credits",
      "Build example gallery (5 presets)",
      "Add error handling for API failures",
      "Write comparison vs raw ChatGPT",
    ],
    category: "ai",
  },
];

export function getTemplate(id: string): ProjectTemplate | undefined {
  return PROJECT_TEMPLATES.find((t) => t.id === id);
}

export function getTemplateList(): Array<{ id: string; name: string; description: string }> {
  return PROJECT_TEMPLATES.map((t) => ({ id: t.id, name: t.name, description: t.description }));
}
